# Generated by Django 3.2.12 on 2023-11-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del grupo (p. ej. Ventas Habana, etc.)', max_length=200)),
            ],
        ),
    ]
