# Generated by Django 3.2.12 on 2023-11-27 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupos',
            name='municipio',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ingrese el nombre del municipio (p. ej. Vinales, etc.)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupos',
            name='provincia',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ingrese el nombre de la provincia (p. ej. Pinar del Rio, La Habana, etc.)', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resumen', models.TextField(help_text='Ingrese una breve descripción del grupo', max_length=1000)),
                ('link', models.CharField(help_text='13 Caracteres <a href=""</a>', max_length=13, verbose_name='LINK')),
                ('grupos', models.ManyToManyField(help_text='Seleccione una provincia para este grupo ', to='catalog.Grupos')),
            ],
        ),
    ]
